# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
     stdlib: "puppetlabs/stdlib"
     translate: "puppetlabs/translate"
     concat: "puppetlabs/concat"
     apt: "puppetlabs/apt"
     postgresql: "puppetlabs/postgresql"
